spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/swift_order
spring.datasource.username=postgres
spring.datasource.password=tcarretera9
app.frontend.url=http://localhost:5173