#Cuando te conectas con postgrest o mysql
#spring.application.name=backend
#spring.datasource.url=jdbc:postgresql://localhost:5432/swift_order
#spring.datasource.username=postgres
#spring.datasource.password=tcarretera9

#pdb
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/TEST_1
#schema/user(simulan la bd)
spring.datasource.username=medicine_calendar
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#spring.jpa.hibernate.ddl-auto=create
#con esta pripiedad decimos crea las tablas o actualizalas cada que se levanta el back, depende si agg un nuevo atributo a los modelos 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

app.frontend.url=http://localhost:5173

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.trigger-file=.reloadtrigger


#para los atributos como last_name 
spring.jackson.property-naming-strategy=SNAKE_CASE


spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s


jwt.secret=mi_clave_super_secreta_para_desarrollo_2026
#jwt.expiration=86400000
jwt.access-expiration=300000
#60000=1 minuto
#300000=5 minutos
jwt.refresh-expiration=604800000
#7 dias=604800000
#300000